name: Deploy Emscripten build to Github Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: emscripten-core/setup-emsdk@v15
        with:
          version: 3.1.68
          cache-key: emsdk-cache-${{ runner.os }}

      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Configure and build web version
        run: |
          mkdir -p build-web
          cd build-web
          emcmake cmake  -B . -S .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_EXE_LINKER_FLAGS="-sUSE_SDL=3" \
            --shell-file ${CMAKE_CURRENT_SOURCE_DIR}/shell.html
          cmake --build . --config Release

      - name: Prepare deployment folder
        run: |
          mkdir -p _site
          cp -r build-web/* _site/

      - name: Upload Github Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
